name: drivvo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  circular_menu: ^4.0.0
  fl_chart: ^1.1.1
  get: ^4.7.3
  get_storage: ^2.1.1
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.6.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  url_launcher: ^6.3.2

  #notifications
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1

  #share export
  path_provider: ^2.1.5
  share_plus: ^12.0.1

  #iap
  connectivity_plus: ^7.0.0
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+8
  in_app_purchase_storekit: ^0.4.7

  #firebase
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  google_sign_in: ^6.3.0
  firebase_database: ^12.1.1
  cloud_functions: ^6.0.5
  firebase_storage: ^13.0.5
  firebase_app_check: ^0.4.1+3
  file_picker: ^10.3.8
  #firebase_analytics: ^12.1.0
  
dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/images/reports/
    - assets/images/more/
    - assets/images/logos/
    - assets/images/plan/

  fonts:
    - family: D-FONT-R
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          style: normal
    - family: D-FONT-M
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
          style: normal
    - family: U-FONT-R
      fonts:
        - asset: assets/fonts/Alvi-Nastaleeq-Regular.ttf
        
